# Generated by Django 5.2 on 2025-04-09 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalikha_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_unit', models.CharField(help_text='e.g.: 4 kg, 5 pcs', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used (Like New)', 'Used (Like New)'), ('Used (Good)', 'Used (Good)'), ('Used (Fair)', 'Used (Fair)')], max_length=20)),
                ('type', models.CharField(choices=[('Textiles', 'Textiles'), ('Plastics', 'Plastics'), ('Wood', 'Wood'), ('Paper/Cardboard', 'Paper/Cardboard'), ('Glass Bottles', 'Glass Bottles')], max_length=50)),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalikha_api.materialcategory')),
                ('resource_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalikha_api.resourcelisting')),
            ],
            options={
                'verbose_name_plural': 'Resource Materials',
            },
        ),
    ]
