# Generated by Django 5.2 on 2025-04-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalikha_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcyclerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProviderProfile',
        ),
        migrations.DeleteModel(
            name='UpcyclerProfile',
        ),
    ]
